<?php

/* custom mdule */

function contact_us_form_alter(&$form, &$form_state, $form_id) {
	if(strstr($form_id, 'webform_client_form_1')) { 

    $nid = $form['#node']->nid;
    $form['actions']['submit']['#ajax'] = array(
      'callback' => 'contact_us_webform_js_submit',
      'wrapper' => 'webform-client-form-' . $nid,
      'method' => 'replace',
      'effect' => 'fade',
    );


		 
		 return $form;
	
	}
	
}

function contact_us_webform_js_submit($form, $form_state) {
  $sid = $form_state['values']['details']['sid'];
  if ($sid) {
    $node = node_load($form_state['values']['details']['nid']);
    $confirmation = array(
      '#type' => 'markup',
      '#markup' => check_markup($node->webform['confirmation'], $node->webform['confirmation_format'], '', TRUE),
    );
		$form = $confirmation;
		
    return $form;
  }
  else {
    return $form;
  }
}
